# -*-shell-script-*-
export PATH=$HOME/code/k8s.gapfish.com/bin:$HOME/code/scripts:$HOME/.rvm/bin:$HOME/.cabal/bin:/usr/local/heroku/bin:$HOME/code/living-in-a-box/bin:/usr/local/heroku/bin:$HOME/code/pdftk_docker/bin:$PATH
# added by Anaconda2 2.4.1 installer
# export PATH="/home/sebastian/.anaconda2/bin:$PATH"
export TERM=xterm-256color
export PROJECT_PATHS=$HOME/code
export EDITOR="emacsclient --alternate-editor=''"
export NVM_DIR=$HOME/.nvm
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.kube/gcloud_gke_credentials.json

# export LANG="en_US.UTF-8"
# export LANGUAGE="en_US:en"
export LC_CTYPE="en_US.UTF-8"
# export LC_NUMERIC="en_US.UTF-8"
# export LC_TIME="en_US.UTF-8"
# export LC_COLLATE="en_US.UTF-8"
# export LC_MONETARY="en_US.UTF-8"
# export LC_MESSAGES="en_US.UTF-8"
# export LC_PAPER="en_US.UTF-8"
# export LC_NAME="en_US.UTF-8"
# export LC_ADDRESS="en_US.UTF-8"
# export LC_TELEPHONE="en_US.UTF-8"
# export LC_MEASUREMENT="en_US.UTF-8"
# export LC_IDENTIFICATION="en_US.UTF-8"
