# -*-shell-script-*-
export PATH=$HOME/code/scripts:$HOME/code/gapfish/keys/bin:$HOME/.go/bin:/usr/local/texlive/2022basic/bin/universal-darwin:$PATH
export TERM=xterm-256color
export PROJECT_PATHS=($HOME/code $HOME/code/gapfish $HOME/code/mewug)
export EDITOR="emacs -Q"
export NVM_DIR=$HOME/.nvm
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.kube/gcloud_gke_credentials.json
export CLOUDSDK_PYTHON=$HOME/.pyenv/versions/3.10.13/bin/python
export GOPATH=$HOME/.gocode
export PASSWORD_STORE_DIR=$HOME/code/gapfish/pass

export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=" -R"

export GPG_TTY=$(tty)

export LANG="en_US.UTF-8"
# export LANGUAGE="en_US:en"
export LC_CTYPE="en_US.UTF-8"
# export LC_NUMERIC="en_US.UTF-8"
# export LC_TIME="en_US.UTF-8"
# export LC_COLLATE="en_US.UTF-8"
# export LC_MONETARY="en_US.UTF-8"
# export LC_MESSAGES="en_US.UTF-8"
# export LC_PAPER="en_US.UTF-8"
# export LC_NAME="en_US.UTF-8"
# export LC_ADDRESS="en_US.UTF-8"
# export LC_TELEPHONE="en_US.UTF-8"
# export LC_MEASUREMENT="en_US.UTF-8"
# export LC_IDENTIFICATION="en_US.UTF-8"

# unset LANG
unset LANGUAGE
# unset LC_CTYPE
unset LC_NUMERIC
unset LC_TIME
unset LC_COLLATE
unset LC_MONETARY
unset LC_MESSAGES
unset LC_PAPER
unset LC_NAME
unset LC_ADDRESS
unset LC_TELEPHONE
unset LC_MEASUREMENT
unset LC_IDENTIFICATION
