# -*-shell-script-*-
ZSH=$HOME/.oh-my-zsh

ZSH_THEME=schasse
COMPLETION_WAITING_DOTS=true

plugins=(rails git rvm pj tmuxinator hub mvn catimg autojump docker)

export UPDATE_ZSH_DAYS=1

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

export HISTSIZE=2147483647
export SAVEHIST=$HISTSIZE

# aliases
alias p='pj '

alias gca='git commit -a'
alias gcan='git commit -an'
alias gsp='g stash && ggpull && g stash pop'
alias grsp='g reset HEAD~1 && gsp'
alias ga='git add --all'
alias ggp='git push origin $(current_branch)'
alias gamend='git add --all && git commit --amend --no-edit'
alias gm='GIT_MERGE_AUTOEDIT=no git merge'
alias be='bundle exec '
alias cpc='cap production rails:console'
alias csc='cap staging rails:console'
alias csd='cap staging deploy'
alias sd='script/staging_deploy'
alias rt='rspec -f documentation'
alias zt='zeus test'
alias ztm='zeus test spec/models'
alias zc='zeus console'
alias cdg='p gapfish'
alias cdb='p boostify'
alias h='nocorrect heroku'

alias genctags='ctags-exuberant -f TAGS --extra=-f --languages=-javascript --exclude=.git --exclude=log -e -R . $(rvm gemdir)/gems/'

alias m2e='mvn eclipse:clean eclipse:eclipse -DdownloadJavadocs=true'\
  ' -DdownloadSources=true'
alias m2i='mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true'
alias m2l='mvn eclipse:clean eclipse:eclipse clean package'\
  ' -DdownloadJavadocs=true -DdownloadSources=true -Dmaven.test.skip=true'\
  ' -Dmaven.javadoc.skip=true -Pedu'
alias m2p='mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true'
alias m2t='mvn test'
alias m2a='mvn assembly:single'

alias e="emacsclient --tty --alternate-editor=''"
alias ec='emacsclient --create-frame &'
alias eq='emacs -nw -q'
# alias vim="emacsclient --tty --alternate-editor=''"
# alias vi="emacsclient --tty --alternate-editor=''"
alias ekill="emacsclient -e '(kill-emacs)'"

alias ai='sudo apt-get install'
alias au='sudo apt-get update'
alias acs='apt-cache search'
alias ds='dpkg -l | grep '

alias hs='history | grep -i '

alias dsh="SYNC_DOTFILES=1 DOTFILES='.zsh .zshrc .gitconfig .rspec .pry_history .oh-my-zsh .oh-my-zsh/custom/schasse.zsh-theme' dev shell"
alias cds='cdg && dsh'

alias -g G='| grep -n'
alias -g L='| less -R'

alias -s html='xdg-open'
alias o='xdg-open'

alias d='docker '
alias dc='docker-compose'
alias dcr='docker-compose run --rm --service'

alias dokku='ssh dokku '

# [[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
# [[ -s $HOME/.jenv/bin/jenv-init.sh ]] && source $HOME/.jenv/bin/jenv-init.sh && source $HOME/.jenv/commands/completion.sh
# [[ -s $NVM_DIR/nvm.sh ]] && source $NVM_DIR/nvm.sh
# this completion shit may break something
# [[ -r $NVM_DIR/bash_completion ]] && source $NVM_DIR/bash_completion

# added by travis gem
# [ -f /home/sebastian/.travis/travis.sh ] && source /home/sebastian/.travis/travis.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source <(kubectl completion zsh)
