# -*-shell-script-*-
ZSH=$HOME/.oh-my-zsh

ZSH_THEME=schasse
COMPLETION_WAITING_DOTS=true

plugins=(rails git rvm pj tmuxinator hub mvn catimg autojump docker)

export UPDATE_ZSH_DAYS=1

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

export HISTSIZE=2147483647
export SAVEHIST=$HISTSIZE

# aliases
alias rm="echo Use 'del', or the full path i.e. '/bin/rm' && ~/rm"
alias del='rmtrash'

alias -g -- clip='xclip -i -selection clipboard'

alias g='hub'
alias ci='g ci-status -v'
alias prs='g pr list --sort-ascending -f"%sC%>(8)%i%Creset  %t%  l %U%n"'
alias gca='git commit -a'
alias gy='git yolo '
alias gcan='git commit -an'
alias gsp='g stash && ggpull && g stash pop'
alias grsp='g reset HEAD~1 && gsp'
alias ga='git add --all'
alias ggp='git push origin $(current_branch)'
alias gamend='git add --all && git commit --amend --no-edit'
alias gm='GIT_MERGE_AUTOEDIT=no git merge'
alias gr='git recent'
alias -g -- -fl='--force-with-lease'
alias be='bundle exec '
alias cpc='cap production rails:console'
alias sd='script/staging_deploy'
alias pg='p gapfish/gapfish'
alias h='nocorrect heroku'

alias skd='systemctl --user start dinkube && kc config use-context admin@din'
alias skg='systemctl --user stop dinkube && kc config use-context admin@gapfish'

alias genctags='ctags-exuberant -f TAGS --extra=-f --languages=-javascript --exclude=.git --exclude=log -e -R . $(rvm gemdir)/gems/'

alias m2e='mvn eclipse:clean eclipse:eclipse -DdownloadJavadocs=true'\
  ' -DdownloadSources=true'
alias m2i='mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true'
alias m2l='mvn eclipse:clean eclipse:eclipse clean package'\
  ' -DdownloadJavadocs=true -DdownloadSources=true -Dmaven.test.skip=true'\
  ' -Dmaven.javadoc.skip=true -Pedu'
alias m2p='mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true'
alias m2t='mvn test'
alias m2a='mvn assembly:single'

alias e="emacsclient --tty --alternate-editor=''"
alias ec='emacsclient --create-frame &'
alias eq='emacs -nw -q'
# alias vim="emacsclient --tty --alternate-editor=''"
# alias vi="emacsclient --tty --alternate-editor=''"
alias ekill="emacsclient -e '(kill-emacs)'"

alias ai='sudo apt-get install'
alias au='sudo apt-get update'
alias acs='apt-cache search'
alias ds='dpkg -l | grep '

alias hs='history | grep -i '

alias dsh="SYNC_DOTFILES=1 DOTFILES='.zsh .zshrc .gitconfig .rspec .pry_history .oh-my-zsh .oh-my-zsh/custom/schasse.zsh-theme' dev shell"
alias cds='cdg && dsh'

alias -g G='| grep -n'
alias -g L='| less -R'
alias wa='watch --color --interval 1 '
alias dff='colordiff '

alias -s html='xdg-open'
alias o='xdg-open'

alias d='docker '
alias dc='docker-compose'
alias dcr='docker-compose run --rm --service-ports'
alias dcb='TAG=`depctl tag` docker-compose build'
alias dcp='TAG=`depctl tag` docker-compose push'

alias k=kubectl
alias kg='k get'
alias kl='k logs --tail=50 --follow=true'
alias ke='k edit'
alias kd='k describe'
alias kdel='k delete'
alias kaf='k apply -f'
alias keti='k exec -ti'
alias kcuc='k config use-context'
alias kccc='k config current-context'
alias kgp="k get pods --field-selector='status.phase!=Succeeded,status.phase!=Failed'"
alias kep='k edit pods'
alias kdp='k describe pods'
alias kdelp='k delete pods'
alias kgs='k get svc'
alias kes='k edit svc'
alias kds='k describe svc'
alias kdels='k delete svc'
alias kgsec='k get secret'
alias kdsec='k describe secret'
alias kdelsec='k delete secret'
alias kgd='k get deployment'
alias ked='k edit deployment'
alias kdd='k describe deployment'
alias kdeld='k delete deployment'
alias ksd='k scale deployment'
alias krsd='k rollout status deployment'
alias kgrs='k get rs'
alias krh='k rollout history'
alias kru='k rollout undo'
alias kgn='k get pods'
alias kdn='k describe pods'

alias -g -- -lo='--selector app=operations'
alias -g -- -lus='--selector app=user-and-support'
alias -g -- -lp='--selector app=prophet'
alias -g -- -ldep='--selector app=deployer'
alias -g -- -lrc='--selector app=redis-cluster'
alias -g -- -lda='--selector app=dashboard'
alias -g -- -ll='--selector app=gapfish-login'
alias -g -- -lrs='--selector app=rewe-sftp'
alias -g -- -lm='--selector app=mongo'
alias -g -- -lgu='--selector app=gem-updater'
alias -g -- -ngs='--namespace gapfish-system'

unalias rg # was rails generate, now is ripgrep

# [[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
# [[ -s $HOME/.jenv/bin/jenv-init.sh ]] && source $HOME/.jenv/bin/jenv-init.sh && source $HOME/.jenv/commands/completion.sh
# [[ -s $NVM_DIR/nvm.sh ]] && source $NVM_DIR/nvm.sh
# this completion shit may break something
# [[ -r $NVM_DIR/bash_completion ]] && source $NVM_DIR/bash_completion

# added by travis gem
# [ -f /home/sebastian/.travis/travis.sh ] && source /home/sebastian/.travis/travis.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source <(kubectl completion zsh 2>/dev/null)

export PATH=$HOME/.pyenv/bin:$PATH
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

p() {
  pj "$@"
  tmux rename-window "$*"
}
compdef _pj p

if [ -z "$TMUX" ]; then
  tmux
fi
