#!/bin/sh

sudo apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"
sudo apt-add-repository ppa:cassou/emacs
sudo apt-add-repository ppa:nesthib/weechat-stable

sudo apt-get update

sudo apt-get install \
  account-plugin-irc \
  chromium-browser \
  curl \
  default-jre \
  emacs24 \
  exuberant-ctags \
  git \
  gnome-tweak-tool \
  gparted \
  inkscape \
  iotop \
  lxc-docker \
  lynx \
  mixxx \
  mplayer \
  network-manager-openconnect-gnome \
  nmap \
  p7zip-full \
  pwgen \
  ruby2.0 \
  skype \
  tmux \
  traceroute \
  tree \
  unclutter \
  vlc \
  weechat \
  whois \
  xclip
