#!/bin/bash -x

sudo apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"
# sudo apt-add-repository "deb http://linux.dropbox.com/ubuntu/ $(lsb_release -sc) main"
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo apt-add-repository "deb https://apt.dockerproject.org/repo ubuntu-xenial main"

sudo apt-get update

sudo apt-get install \
     aspell-de \
     aspell-en \
     autojump \
     curl \
     default-jre \
     editorconfig \
     emacs24 \
     exuberant-ctags \
     iotop \
     docker-engine \
     docker-compose \
     git \
     iotop \
     lynx \
     nmap \
     p7zip-full \
     pwgen \
     redshift \
     shellcheck \
     silversearcher-ag \
     tmux \
     traceroute \
     tree \
     unclutter \
     whois \
     xclip \
     zsh

# if there is a graphical environment
if [[ -n "${DISPLAY}" ]]; then
  sudo apt-get install \
       backintime-gnome \
       chromium-browser \
       gnome-tweak-tool \
       gparted \
       inkscape \
       mplayer \
       network-manager-openconnect-gnome \
       vlc
fi
