#!/bin/bash

sudo apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"
sudo apt-add-repository 'ppa:ubuntu-elisp/ppa'
sudo apt-add-repository 'ppa:nesthib/weechat-stable'
sudo apt-add-repository "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -sc) main"
sudo apt-key adv \
   --keyserver 'pgp.mit.edu' \
   --recv-keys '58118E89F3A912897C070ADBF76221572C52609D'
sudo apt-add-repository 'ppa:zeal-developers/ppa'
sudo apt-key adv --keyserver 'pgp.mit.edu' --recv-keys '5044912E'
# sudo apt-add-repository "deb http://linux.dropbox.com/ubuntu/ $(lsb_release -sc) main"

sudo apt-get update

sudo apt-get install \
  aspell-de \
  autojump \
  curl \
  default-jre \
  editorconfig \
  emacs24 \
  exuberant-ctags \
  git \
  iotop \
  docker-engine \
  lynx \
  nmap \
  p7zip-full \
  pwgen \
  shellcheck \
  tmux \
  traceroute \
  tree \
  unclutter \
  weechat \
  whois \
  xclip \
  zsh

# if there is a graphical environment
if [[ -n "${DISPLAY}" ]]; then
  sudo apt-get install \
    backintime-gnome \
    chromium-browser \
    dropbox \
    gnome-tweak-tool \
    gparted \
    inkscape \
    mixxx \
    mplayer \
    network-manager-openconnect-gnome \
    python-gpgme \
    skype \
    vlc \
    zeal
fi
