#!/bin/bash -x

sudo apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"

# sudo apt-add-repository "deb http://linux.dropbox.com/ubuntu/ $(lsb_release -sc) main"

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# arc-theme
# wget -O- http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key | sudo apt-key add -
# sudo apt-add-repository "deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /"

sudo apt-add-repository "deb https://packages.cloud.google.com/apt cloud-sdk main"
wget -O- https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo add-apt-repository ppa:mmstick76/alacritty

sudo apt-get update

sudo apt-get install \
     alacritty \
     aspell-de \
     aspell-en \
     autojump \
     colordiff \
     curl \
     default-jre \
     editorconfig \
     emacs-nox \
     exuberant-ctags \
     iotop \
     docker-ce docker-ce-cli containerd.io \
     git \
     google-cloud-sdk \
     iotop \
     source-highlight \
     lynx \
     nmap \
     pass \
     p7zip-full \
     pwgen \
     redshift \
     ruby \
     shellcheck \
     silversearcher-ag \
     tmux \
     traceroute \
     trash-cli \
     tree \
     unclutter \
     whois \
     xclip \
     zsh

# if there is a graphical environment
# if [[ -n "${DISPLAY}" ]]; then
#   sudo apt-get install \
#        backintime-qt \
#        chromium-browser \
#        gnome-tweak-tool \
#        gnupg2 pcscd scdaemon \
#        gparted \
#        inkscape \
#        mplayer \
#        network-manager-openconnect-gnome \
#        dkms \
#        vlc
#   # virtualbox-5.1 installation fails, try virtualbox instead :(
# fi

# sudo gem install tmuxinator pry
# sudo pip install docker-compose
