#!/bin/bash

# this script will be triggered by
# my adjustion of .oh-my-zsh/tools/check_for_upgrade.sh

git_dirty() {
  echo $(git status -s --untracked-files=no | tail -n1)
}

fail_upgrade() {
  printf '\033[0;31m%s\033[0m\n' 'There was an error updating. Try again later?'
  exit 1
}

update_with_git() {
  git_was_dirty=$(git_dirty)

  if [[ -n ${git_was_dirty} ]]; then
    git add . && git stash save
  fi

  if ! git pull --rebase --stat origin master; then
    fail_upgrade
  fi

  if [[ -n ${git_was_dirty} ]]; then
    git stash pop
  fi
}

# upgrade system
printf '\033[0;34m%s\033[0m\n' 'Upgrading system'
sudo apt-get update
sudo apt-get upgrade

# upgrade oh-my-zsh (copied from ~/.oh-my-zsh/tools/upgrade.sh)
printf '\033[0;34m%s\033[0m\n' 'Upgrading Oh My Zsh'
cd ~/.oh-my-zsh
update_with_git
printf '\033[0;32m%s\033[0m\n' '         __                                     __   '
printf '\033[0;32m%s\033[0m\n' '  ____  / /_     ____ ___  __  __   ____  _____/ /_  '
printf '\033[0;32m%s\033[0m\n' ' / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ '
printf '\033[0;32m%s\033[0m\n' '/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / '
printf '\033[0;32m%s\033[0m\n' '\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  '
printf '\033[0;32m%s\033[0m\n' '                        /____/                       '
printf '\033[0;34m%s\033[0m\n' 'Hooray! Oh My Zsh has been updated and/or is at the current version.'
printf '\033[0;34m%s\033[1m%s\033[0m\n' 'To keep up on the latest news and updates, follow us on twitter: ' 'http://twitter.com/ohmyzsh'
printf '\033[0;34m%s\033[1m%s\033[0m\n' 'Get your Oh My Zsh swag at: ' 'http://shop.planetargon.com/'

# upgrade dotfiles
printf '\033[0;34m%s\033[0m\n' 'Upgrading schasse/dotfiles'
cd ~/.dotfiles
update_with_git
printf '\033[0;34m%s\033[0m\n' 'schasse/dotfiles has been updated and/or is at the current version.'

# upgrade prelude
printf '\033[0;34m%s\033[0m\n' 'Upgrading Prelude'
cd ~/.emacs.d
update_with_git
printf '\033[0;34m%s\033[0m\n' 'Prelude has been updated and/or is at the current version.'
